language: node_js
node_js:
  - "8.0"
yarn:
  - "1.5.0"
before_script:
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
script:
  - yarn jshint *.js lib
after_script:
  - yarn build
  - yarn test-coveralls
  - cd test/node && yarn  && node app.js

